nelmio_api_doc:
    documentation:
        info:
            title: Symfony Demo
            description: This is an demo project based on Symfony6.1!
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc

